#!/bin/bash

#-------------------------------------------------------------------------------

# Copyright 2015 Actian Corporation
 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
 
# http://www.apache.org/licenses/LICENSE-2.0
 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#-------------------------------------------------------------------------------

# This script runs the SQL generated by TPC_DS_Run.sh from the TPC SQL templates.

# It is written as an independent script to allow the tests to be run separately
# without having to run TPS_DS_Run.sh which would re-create all the data which
# can be time intensive.

#-------------------------------------------------------------------------------

set -e

# Assume if SQL_DIR not set then called independently. Hence set essentail variables.
if [ "${SQL_DIR}" == "" ]; then
    TPC_DB=tpc_db
    SQL_DIR=TPC_SQL_SCRIPTS
    LOG_DIR=LOG_FILES
    LOG_FILE=${LOG_DIR}/TPC_DS_Summary_Results.txt
    RE_RUN=true
else
    RE_RUN=false 
fi

if [ "${RE_RUN}" = true ]; then
    echo ""
    echo "TPC-DS Style Benchmark - Re-run of tests started"
    echo ""
fi

if [ ! -d ${SQL_DIR} ]; then
    echo "ERROR on startup - This script is being run without previously running TPC_DS_Run.sh"
    exit 9
fi

if [ "`ls ${SQL_DIR} | wc -l`" == "0" ]; then
    echo "ERROR on startup - This script is being run without successfully running TPC_DS_Run.sh"
    exit 9
fi

echo "TPC DS Style SQL Performance Test Results" > ${LOG_FILE}
echo "-----------------------------------------" >> ${LOG_FILE}
echo ""                                          >> ${LOG_FILE}
echo "Run time in seconds"                       >> ${LOG_FILE}
echo ""                                          >> ${LOG_FILE}

for sql_file in $(ls ${PWD}/${SQL_DIR}/*.sql); do

    # Extract the SQL name and no. for the Summary print
    sql_name=`echo ${sql_file} | awk -F 'TPC_SQL_SCRIPTS/' '{print $2}' | awk -F '.' '{print $1}'`
    sql_no=`echo ${sql_file} | awk -F 'TPC_SQL_SCRIPTS/' '{print $2}' | awk -F '.' '{print $1}' | sed 's/Query//'`

    echo "Running SQL Test ${sql_name}."

    # Note time at start of run
    Start_Time="$(date +%s%N)"

    # Run the SQL
    sql_to_run=`cat ${sql_file}; echo "\g"`

    sql ${TPC_DB} > ${LOG_DIR}/TPC_DS_${sql_name}_Results.out <<EOF
${sql_to_run}
EOF

    # Time at end of run and hence calculate duration
    Run_Time="$(($(date +%s%N)-${Start_Time}))"

    # Log the results - run time or FAILED
    if [ `grep "^E_US" ${LOG_DIR}/TPC_DS_${sql_name}_Results.out | wc -l` -gt 0 ]; then
        printf "${sql_name} : FAILED\n" >> ${LOG_FILE}
    else
        printf "${sql_name} : %5.2f\n" `bc <<< "scale = 2; (${Run_Time} / 1000000000)"` >> ${LOG_FILE}
    fi

done

if [ "${RE_RUN}" = true ]; then
    echo ""
    echo "TPC-DS Style Benchmark - Re-run of tests completed successfully"
    echo ""
fi

#------------------------------------------------------------------------------#
#---------------------------- End of Shell Script -----------------------------#
#------------------------------------------------------------------------------#
